---
title: The Discrete Event Simulation Playground
include-back-link: false
page-layout: full
grid:
  sidebar-width: 0px
  body-width: 1100px
  margin-width: 300px
  gutter-width: 1.5rem
---

```{=html}
<style>

body {
	text-align: center;
}

a {
	color: rgb(25, 22, 22);
	text-decoration: underline;
	-webkit-text-decoration: underline;
	-moz-text-decoration: underline;
	-ms-text-decoration: underline;
	-o-text-decoration: underline;
  padding: 2px
}

.custom-button:hover a {
  background-color: white;    /* White background on hover */
  color: #3d3d3d;              /* Grey text on hover */
  border-color: #3498db;      /* Blue border on hover */
}

@media only screen and (max-width: 600px) {

.hsma-iframe {
  height: 350px
}
}

@media only screen and (max-width: 800px) {

.hsma-iframe {
  height: 450px
}
}

@media only screen and (min-width: 800px) {

.hsma-iframe {
  height: 700px
}

}

</style>
```

Discrete Event Simulation is a powerful tool for improving pathways, of which there are a lot in healthcare services.

Originally built for introducing people to Discrete Event Simulation at our HSMA open day, this web application is freely available for you to use and adapt under a [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en) licence.

It gradually introduces key concepts relating to discrete event simulation, including sampling from distributions, the role of random seeds, resources, multiple runs, and more.

Users are able to adjust a range of parameters and rerun the modelk. A range of animations, built using code that would go on to become the vidigi package, help users to develop their understanding of discrete event simulation as a technique, with a range of other visualisations used to guide their attention to important learning points at each stage.

Written using stlite - which brings the power of browser-based python to the Streamlit framework - the tool has been tested with 50+ concurrent users, with the users' hardware undertaking all calculations, minimising hosting requirements.

:::{.callout-note}
Due to the use of browser-based Python, the tool can run slowly on older hardware. It is recommended to be used on a laptop or desktop PC rather than a phone (though a phone will work - slowly - in a pinch!)
:::

```{=html}
<div class="project-link-buttons">
    <ul class="project-links">
        <button class="custom-button"><a href="https://hsma-programme.github.io/Teaching_DES_Concepts_Streamlit/"><i class="fa-solid fa-globe"></i><span style="padding-left: 10px;">Open the Playground in a New Tab</span></a></button>
        <button class="custom-button"><a href="https://github.com/hsma-programme/Teaching_DES_Concepts_Streamlit"><i class="fa-brands fa-github"></i><span style="padding-left: 10px;">View the Code</span></a></button>
    </ul>
</div>
```

Try it out below!

```{=html}
<iframe class="hsma-iframe" width="90%" src="https://hsma-programme.github.io/Teaching_DES_Concepts_Streamlit/" title="HSMA DES Playground"></iframe>
```
